[package]
name = "rustjfssecond"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"
tokio = {version = "1.47.1" , features = ["full"]}
log = "0.4"
env_logger = "0.10"
byteorder = "1.5"
