

name: Build the main branch ( daemon )
on: 
  push:
    branches:
      - "main"
jobs:
  build0-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.24.4'
      - run: |
          git clone https://github.com/kubernetes/code-generator.git  ../code-generator
          cd ../code-generator
          git checkout -b release-1.27
          cd -
          make fsnotify-daemon